### ISSUE TITLE
Error when importing sgf library

### ISSUE THREAD

**Issue by climu** [Awea/wshudan#4]
Adding `const sgf = require('@sabaki/sgf');` in `app.js` results in the folowing.

```
Build failed!

✖ ERROR ../node_modules/@sabaki/sgf/src/parse.js
Module not found: Error: Can't resolve 'fs' in './node_modules/@sabaki/sgf/src'
 @ ../node_modules/@sabaki/sgf/src/parse.js 1:9-22
 @ ../node_modules/@sabaki/sgf/src/main.js
 @ ./components/app.js
 @ ./index.js
 @ ../node_modules/preact-cli/lib/lib/entry.js
 @ multi ../node_modules/preact-cli/lib/lib/entry webpack-dev-server/client webpack/hot/dev-server

```

I did notice [this warning](https://github.com/SabakiHQ/sgf#use-in-the-browser) from sgf docs:

> 
> You can use this library in the browser by using a bundler, such as webpack. If you do, you need to add the following lines to your webpack configuration:
> 
> ```
> {
>     ...
>     externals: {
>         'fs': 'null',
> 
>         // Add the next lines to disable automatic encoding detection
>         // and reduce bundle size:
>         'jschardet': 'null',
>         'iconv-lite': 'null'
>     }
> }
> ```

So I created a `webpack.config.js` containing the above without any help. I changed the content of this file with inspiration from [sabaki dev branch one](https://github.com/SabakiHQ/Sabaki/blob/web/webpack.config.js) without much success.

It seems to me the `webpack.config.js` is not loaded at all. Am I missing anything from our config here?

**Comment by Awea** [comment]
> It seems to me the webpack.config.js is not loaded at all. Am I missing anything from our config here?

Webpack is not part of this project. It use [preact-cli](https://github.com/preactjs/preact-cli) for bundling. 

@climu I'll have a look on @sabaki/sgf to include it to this repo :)

**Comment by climu** [comment]
> @climu I'll have a look on @sabaki/sgf to include it to this repo :)

You are an angel!

**Comment by Awea** [comment]
@climu It's done. But I can't have the library working when I use the `parse` method. Maybe I'm doing something wrong. I let you open another issue on that topic if you can't make it work too.

**Comment by climu** [comment]
@Awea thanks for that!

I think it's a bug in `@sabaki/sgf`. I opened an [issue](
https://github.com/SabakiHQ/sgf/issues/6) there.

In the meantime I made the explained change in my `node-modules` and I had it working. It's ugly but it allow to work in the meantime.

I guess I could open a PR for the fix at `@sabaki/sgf` repo.

**Comment by climu** [comment]
He fixed it already!

**Comment by Awea** [comment]
> He fixed it already!

:ok_hand:
