### ISSUE TITLE
Bundle size

### ISSUE THREAD

**Issue by climu** [Awea/wshudan#5]
Right now when building I have this output:
![image](https://user-images.githubusercontent.com/2648653/69493023-fe7ba780-0ea9-11ea-8e8a-4f7fa941030d.png)

I think it means that the unminified bundle file will be at least 1.73 MB.

I know it's 2019, soon 2020 but still this got me concern.

And I wonder: How can the full sabaki [bundle](https://sabaki.yichuanshen.de/web/bundle.js) that power [this demo](https://sabaki.yichuanshen.de/web/) can be around 250 K?

Could we be packing too much dependencies?
Maybe some configuration somewhere?

I know it's still very early for production concern but I prefer to raise this anyway.

**Comment by Awea** [comment]
@climu How did you build to get those result ? Using `make build`, I got :

![2019-11-24_13-07](https://user-images.githubusercontent.com/630023/69494417-b5345380-0ebb-11ea-89dd-ce5634a7e006.png)

**Comment by climu** [comment]
Oh, I was using `make serve`. Quite a different size!

Sorry about that, node is still quite strange to me.

Thanks!

**Comment by Awea** [comment]
:)
